---
- name: Deploy roles dynamically
  hosts: "{{ HOSTS.split(',') }}"
  become: true

  tasks:
    - name: Apply selected roles
      include_role:
        name: "{{ item }}"
      loop: "{{ ROLES.split(',') }}"



#- name: Deploying ansible roles
 # hosts: webservers
  #become: true
  #roles:
   # - roles/jdk21_role

