doonops_user: doonops
doonops_groups: sudo
doonops_shell: /bin/bash
ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCkV/FPjjLppiwByg03IZWZ7eeN5onUl6aJLXF5/guaoCZ3iNCrL0n4yfOjVwlq9QPkDFngvk2wYydSrc1ekBItDrChDaGJit1AoCOcbG1hmLJql5QcFfaleF7j7HcqMxl4WoND9UHSOsLGQKJuWd57RTELNbEF/p8WwnGordS22ARxYpD50t8rr9VG+dNPtv2SfJ5sXNApt0wsz+qH5jmjJotYy3rzUiIgmYX2UPY7mCt9oiPHYgIF51zTrs93lKNGXC/n6hSs+5iZ/eLE7stTzVMx1RhIrabTqNZ5OcSO4dQs5rkUZijpfq74Ae5lQ125lzBCHBEYf+MJQMvZE3ev"
