- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

- name: Configure elasticsearch.yml
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch

- name: Configure Elasticsearch heap
  template:
    src: heap.options.j2
    dest: /etc/elasticsearch/jvm.options.d/heap.options
  notify: restart elasticsearch
